spring:
#    datasource:
#      url: jdbc:h2:tcp://localhost/~/myspring
#      username:
#      password:
#      driver-class-name: org.h2.Driver
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/temp
    username: root
    password: system
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true



logging.level:
  org.hibernate.SQL: debug