server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db-iks3m.pub-cdb.ntruss.com:3306/daedongje
    username: user
    password: daedongje8719!@
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://daedongje-rds.codczmyir8nu.ap-northeast-2.rds.amazonaws.com:3306/daedongje_db
#    username: admin
#    password: daedongje8719

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
  # swagger
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
